application:
  name: inmobiliaria
  project: inmobiliaria
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: mongodb
  version: "3.6"
  name: my-mongodb-8628210
routers:
- name: main
  routes:
  - application_name: inmobiliaria
    paths:
    - /
