# ---- DOCKER FINLIDADES  -----
# Aplicacion de Liberira
# Queremos distrubuirla, 
# Actualizando miesntras trabajamos
# proteccion ssitema operativo
# Distribuicion facil y comoda.
# 




########### OPCION 1 #################
# build con todos los cambios, mas arapido
# FROM alpine
# RUN apk ADD --no-cache python3-dev &&\
#     pip3 install --upgrade pip


# # copiamos solo los ficheros modificados
# COPY ["main.py", "templates/layout.html", "/app/"]
# WORKDIR /app

# # copiar todo menos los archivos no modificados
# COPY [".", "/app"]

########################################33
############ COPION 2
########################################3
# VOLUMENENS
# docker run --rm -d -p  3000:5000 -v $pwd:/app/src flaskapp 
# docker commit .....




# # Corre nodejs y no me que importa que so corre por detras.
# FROM node:8

# # copia todo hacia la carpeta dentro del contendor
# COPY [".", "/usr/src"]

# # direcotiro trabajo
# WORKDIR /usr/src

# # inciar el npm install
# RUN --no-cache npm install # sin cache

# # activar un puerto que se expone al exteior
# EXPOSE 3000

# # ejecutamos el comando por defecto que se ejecuta un contendor
# # creada esta imagen
# CMD [ "node", "index.js" ]


