# version: "3"
# services:
#   app: 
#     image: "sosan/horo_test"
#     container_name: "nombre_contendor"
#     depends_on: 
#       - db
#     ports: 
#       - "80:5100"
#     volumes:
#       - .:/app # espejo
#       - /static # no tocar static, es posible que nos machaquen.
      
#   db:
#     image: mongo


# servicios = contenedores
# docker-compose up
# docker-compose logs app
# docker-compose exec app /bin/sh
# docker-compose down
# docker-compose scale app=4


# ------- CREAR IMAGEN ---------
version: "3.7"
services:
  app: 
    build: .
    image: "sosan/horo_test"
    # container_name: ""
    depends_on: 
      - db
    ports: 
      - "7000-7010:5000"
    # networks: 
    #   -   
    volumes:
      - .:/app
      
  db:
    container_name: "mongodb"
    image: mongo

